### ISSUE TITLE
Support unescaped content in handlebar template

### ISSUE THREAD

**Issue by jeanlaurent** [CodeStory/code-story-http#5]
Support for triple mustache does not work. This prevent us from using unescaped content. Content already in html comes escaped without this.

Look for `{{{` in handlebar doc for more explanation http://handlebarsjs.com/

**Comment by jeanlaurent** [comment]
Ok this _sort_ of work.
Only by `[[& somecontent ]]` which is good.
Still `[[[somecontent]]]` does not work. But `[[{somecontent}]]` work, which is kind of _super_ ugly
It also work by registering a specific helper...

**Comment by dgageot** [comment]
Won't fix. It's hard coded in the Hbs lexer
